### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by chitrang89** [CatalystCode/ibex-dashboard#122] opened 2017-05-13 03:56 UTC
Hey Guys,

First of all, keep up the great work you guys are doing :) I just tried to clone,compile and run locally but running into compile issues. So far, I've tried to check out other branches but no go, also updated my node version. Im running this on a mac. Here's the screenshot of the compilation error I'm getting. Any advise would be great.

Thanks

<img width="1057" alt="err" src="https://cloud.githubusercontent.com/assets/1250576/26022259/a8c44826-37f4-11e7-9343-0d9c1cd549ad.png">

**Comment by morsh** [comment] 2017-05-13 05:34
@chitrang89 - thanks for the issue, we just merged in a lot of pulls from a hackfest. I'll make sure to check this tomorrow and find out the problem.

**Comment by chitrang89** [comment] 2017-05-13 05:35
Lovely. In the meantime, is there a stable build/branch I could check out?

**Comment by morsh** [comment] 2017-05-13 05:45
@chitrang89 can you try this? 
https://github.com/CatalystCode/ibex-dashboard/tree/fix-adv-dash-templates

I suspect it's a small ta compile error, but I'll only be able to check it tomorrow.

**Comment by morsh** [comment] 2017-05-13 05:58
@chitrang89 -
1. What's your typescript version?
`tsc -v`
2. What are the reproduction steps? I know this code ran on several computers this week (PC/Mac)

**Comment by chitrang89** [comment] 2017-05-13 06:21
2.3.2 - I just downloaded the source, npm install and yarn start:dev

**Comment by morsh** [comment] 2017-05-13 08:11
I'm guessing this is because you're using a newer version of typescript

**Comment by morsh** [comment] 2017-05-14 06:55
Hi,
I tried reproducing by installing typescript 2.3.2, then cloning the repo and rerunning:
`yarn`
`yarn run start:dev`

And I still can't reproduce the problem.

When you're running `yarn run client:start`
I'm seeing the following line in the console (even though I installed the new version of Typescript):
`ts-loader: Using typescript@2.2.1 and C:\temp\ibex-dashboard\tsconfig.json`

If you want, we can have a Skype meeting to understand why this happens on your machine.

**Comment by deadlyfingers** [comment] 2017-05-19 21:04
@chitrang89 I see you mentioned you did `npm install`, but can you try `yarn install` instead? Lmk if this issue still happens and was this the`ibex-version-1.0` or master branch?

**Comment by chitrang89** [comment] 2017-05-20 22:09
Hi Guys,

I just checked out a fresh copy and "connections-bot-framework" branch, ran yarn install and that seems to have done the magic. Thanks so much @deadlyfingers and @morsh for helping me out with this :)

**Closed** 2017-05-21 12:51 UTC
Labels: bug
